# .github/workflows/setup-java.yml
name: Java Setup

on:
  workflow_call:
    inputs:
      run-step:
        required: true
        type: string
    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run step
        run: ${{ inputs.run-step }}
